version: '3'
services:
  back:
    build:
      context: ../../backend/
      dockerfile: prod.dockerfile
    expose:
      - 4040
    ports:
      - 4040:4040
    # volumes:
    #   - ../../backend/:/app/
    environment:
      - PORT=4040
  front:
    build:
      context: ../../frontend/
      dockerfile: prod.dockerfile
    expose:
      - 80
    ports:
      - 80:80
    environment:
      - PORT=80
    # volumes:
    #   - ../../frontend/:/app
    links:
      - back